# Generated by Django 4.2.2 on 2023-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auther',
            field=models.CharField(max_length=100),
        ),
    ]
