# Generated by Django 4.2.2 on 2023-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayone', '0002_alter_book_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dj',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
