# Generated by Django 4.2.2 on 2023-07-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayone', '0003_book_dj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dj',
        ),
    ]
